[package]
name = "autobib-entry"
version = "0.2.0"
authors = ["Alex Rutar <alex@rutar.org>", "Peiran Wu"]
description = "Entry data backend for the Autobib CLI"
repository = "https://github.com/autobib/autobib-entry"
homepage = "https://github.com/autobib/autobib-entry"
license = "AGPL-3.0-or-later"
readme = "README.md"
keywords = ["bibtex", "biblatex", "bibliography"]
rust-version = "1.96"
edition = "2024"

[features]
v0 = ["dep:thiserror"]

[dependencies]
phf = { version = "0.14.0", features = ["macros"] }
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_bibtex = "0.7.1"
thiserror = { version = "2.0.19", optional = true }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "data"
harness = false
required-features = ["v0"]
